version: 2
jobs:
  build:
      docker:
      - image: circleci/ruby:2.7.1
        environment:
          RAILS_ENV: test

      - image: circleci/postgres:12-alpine-ram
    steps:
      - checkout

      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            - bundle-

      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: bundle exec rake db:create db:migrate

      - run:
          name: Run rspec
          command: bundle exec rspec
